services:
  - type: web
    name: gymfit-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: sqlite
